"""
Seth Bot Configuration
Loads environment variables and bot settings
"""
import os
from dotenv import load_dotenv
# Load environment variables
load_dotenv()
# Bot Configuration
DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
BOT_PREFIX = os.getenv('BOT_PREFIX', '!')
# Database Configuration
DATABASE_PATH = 'data/seth.db'

# Game Configuration
STARTING_HEALTH = 100
STARTING_HUNGER = 0
MAX_HUNGER = 100
MINE_COOLDOWN = 60  # seconds
PREMIUM_MINE_COOLDOWN = 30  # seconds for premium users

# Game Defaults
STARTING_FOOD = 5
STARTING_MEDICINE = 2
STARTING_COAL = 0
MAX_HEALTH = 100
MIN_HEALTH = 0
MAX_RELATIONSHIP = 100
MIN_RELATIONSHIP = 0
DEFAULT_RELATIONSHIP_SCORE = 50

# Decay System
DECAY_INTERVAL = 120          # seconds between decay cycles
HUNGER_PER_CYCLE = 5
NATURAL_DECAY = 1             # base health loss per cycle
SEVERE_HUNGER_THRESHOLD = 80
SEVERE_HUNGER_DAMAGE = 3
MODERATE_HUNGER_THRESHOLD = 50
MODERATE_HUNGER_DAMAGE = 1

# Maintenance
FEED_HUNGER_REDUCTION = 30
HEAL_HEALTH_RESTORATION = 25
TEST_DAMAGE_HEALTH = 20
TEST_DAMAGE_HUNGER = 20

# Mining Ranges
FOOD_MINE_MIN = 0
FOOD_MINE_MAX = 2
MEDICINE_MINE_MIN = 0
MEDICINE_MINE_MAX = 1
COAL_MINE_MIN = 1
COAL_MINE_MAX = 5

# Trading
MAX_TRADE_AMOUNT = 100
TRADE_TIMEOUT = 30.0

# Status Display Thresholds
HEALTH_EXCELLENT_THRESHOLD = 80
HEALTH_GOOD_THRESHOLD = 60
HEALTH_FAIR_THRESHOLD = 40
HEALTH_POOR_THRESHOLD = 20
HUNGER_SATISFIED_THRESHOLD = 20
HUNGER_PECKISH_THRESHOLD = 40
HUNGER_HUNGRY_THRESHOLD = 60
HUNGER_STARVING_THRESHOLD = 80

# Health Color Thresholds
HEALTH_COLOR_GREEN_THRESHOLD = 70
HEALTH_COLOR_RED_THRESHOLD = 30

# Public Display Thresholds
HEALTH_GOOD_DISPLAY = 75
HEALTH_POOR_DISPLAY = 25
HUNGER_STARVING_DISPLAY = 80
HUNGER_HUNGRY_DISPLAY = 50

# Warning Thresholds (decay system)
HEALTH_CRITICAL_WARNING = 10
HUNGER_CRITICAL_WARNING = 70

# Status Command Thresholds
HEALTH_CRITICAL_STATUS = 20
HUNGER_CRITICAL_STATUS = 80
HEALTH_WARNING_STATUS = 40
HUNGER_WARNING_STATUS = 60

# Score Calculation
GENERATION_SCORE_WEIGHT = 10
AGE_SCORE_DIVISOR = 10

# Visual Bars
BAR_SEGMENTS = 10
BAR_PERCENTAGE_MAX = 100

# Time Constants
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400

# Drama System
DRAMA_VOTE_DURATION = 180     # seconds
ROMANCE_DRAMA_CHANCE = 0.4
CONFLICT_DRAMA_CHANCE = 0.5
FIGHT_OUTCOME_CHANCE = 0.5
LOVERS_THRESHOLD = 80
FRIENDS_THRESHOLD = 60
NEUTRAL_THRESHOLD = 40
RIVALS_THRESHOLD = 20

# Drama Relationship Changes
RECONCILE_BONUS = 20
BREAKUP_PENALTY = -30
FIGHT_PENALTY = -20
FORGIVE_BONUS = 10
JUSTICE_PENALTY = -40
DRAMA_SPREAD_PENALTY = -10
SUPPORT_BONUS = 15
OPPOSE_PENALTY = -15
ALLIANCE_BONUS = 15
SCANDAL_PENALTY = -20

# Maintenance warning thresholds (same values used in multiple cogs)
HEALTH_CRITICAL_MAINT = 20
HUNGER_STARVING_MAINT = 80


def verify_token() -> None:
    """Call this before starting the bot, not on import"""
    if not DISCORD_TOKEN:
        raise ValueError("No Discord token found! Add DISCORD_TOKEN to .env file")
    print(f"✅ Config loaded! Prefix: {BOT_PREFIX}")
